# Generated by Django 4.2.30 on 2026-05-11 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Număr Apartament')),
                ('floor', models.IntegerField(verbose_name='Etaj')),
                ('rooms', models.IntegerField(default=2, verbose_name='Număr Camere')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Suprafață (mp)')),
                ('status', models.CharField(choices=[('occupied', 'Ocupat'), ('vacant', 'Liber'), ('maintenance', 'În Mentenanță')], default='vacant', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apartament',
                'verbose_name_plural': 'Apartamente',
                'ordering': ['block', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume Bloc')),
                ('address', models.CharField(max_length=200, verbose_name='Adresă')),
                ('number_of_floors', models.IntegerField(default=1, verbose_name='Număr Etaje')),
                ('city', models.CharField(default='București', max_length=100, verbose_name='Oraș')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocuri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='management.apartment', verbose_name='Apartament')),
            ],
            options={
                'verbose_name': 'Rezident',
                'verbose_name_plural': 'Rezidenți',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_managers', to='management.block', verbose_name='Bloc')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Manageri',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='management.block', verbose_name='Bloc'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('bloc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bloc Administrant')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descriere')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Începerii')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Încheierii')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_administrators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administratori',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
