# Generated by Django 4.2.30 on 2026-05-11 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=100, verbose_name='Nume Rezident')),
                ('apartment_number', models.CharField(max_length=20, verbose_name='Număr Apartament')),
                ('issue_type', models.CharField(choices=[('plumbing', 'Instalație Sanitară'), ('electrical', 'Instalație Electrică'), ('structural', 'Structural'), ('cleaning', 'Curățenie'), ('security', 'Securitate'), ('other', 'Altele')], max_length=20, verbose_name='Tip Problemă')),
                ('description', models.TextField(max_length=1000, verbose_name='Descriere')),
                ('status', models.CharField(choices=[('pending', 'În Așteptare'), ('in_progress', 'În Progres'), ('resolved', 'Rezolvat'), ('rejected', 'Respins')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Rezolvat la')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Raportat de')),
            ],
            options={
                'verbose_name': 'Problemă Raportată',
                'verbose_name_plural': 'Probleme Raportate',
                'ordering': ['-created_at'],
            },
        ),
    ]
