# Generated by Django 4.1.4 on 2023-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=15, null=True)),
                ("last_name", models.CharField(max_length=15, null=True)),
                ("age", models.IntegerField()),
                ("is_olympic", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=20, null=True)),
                ("description", models.TextField(max_length=300, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
