# Generated by Django 4.1.4 on 2023-01-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
