# Generated by Django 4.1.4 on 2023-01-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0006_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residents",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
