# Generated by Django 4.1.4 on 2023-01-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        ("residents", "0007_alter_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="residents",
            name="management",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.management",
            ),
        ),
    ]
