# Generated by Django 4.1.4 on 2023-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0008_student_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="residents",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=6,
                null=True,
            ),
        ),
    ]
